package by.epam.store.controller.command;

public enum CommandType {
	FIND_ALL_USERS, 
	FIND_USERS_BY_NAME,
	DEFAULT,
	SIGN_IN,
	GO_TO_MAIN_PAGE,
	EN,
	RU,
	SIGN_UP,
	CONFIRM_REGISTRATION,
	SIGN_OUT,
	FORGOT_PASSWORD,
	SHOW_PRODUCTS_FROM_CATEGORY
}
