package by.epam.store.controller.command;

public enum CommandType {
	FIND_ALL_USERS, 
	FIND_USERS_BY_NAME,
	DEFAULT,
	SIGN_IN,
	GO_TO_MAIN_PAGE,
	EN,
	RU,
	SIGN_UP,
	CONFIRM_REGISTRATION,
	SIGN_OUT,
	FORGOT_PASSWORD,
	SHOW_PRODUCTS_FROM_CATEGORY,
	FIND_PRODUCTS_BY_NAME,
	ADD_PRODUCT_TO_BASKET,
	ADD_PRODUCT_TO_CATALOG,
	GO_TO_BASKET_PAGE
}
